# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d47939bf2b1dc776fad26440e23b1275b11f997265a756fcd6103b38e8d0be8f5089dcbbc435aebd9acea10ab4034c01a9d8b77ba1ff98e524e592b2382fe4dc

test:
  secret_key_base: 7e0ad17149cd87c0e38846db3f8ec4efd6662ac20e4fc7c0c51c11ea6451d3b568e0e1a207c81b94adae5dc3b0118fa424649f242df75ff9223c098a92b67129

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
